services:
  learnpyapp:
    build: .
    working_dir: /learnpyapp
    volumes:
      - ./:/learnpyapp
    ports:
      - "8000:8000"
    command: uvicorn learnpyapp.api:app --host 0.0.0.0 --port 8000
